# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported

use_modular_headers!

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'NationalHonorSociety' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true  # or false to disable
    # Removed flipper_configuration since it's not being used
  )

  pod 'FirebaseCoreInternal'
  pod 'GoogleUtilities'
  # Pods for react-native-ble-manager
  pod 'BleManager', :path => '../node_modules/react-native-ble-manager'
  # Pod for react-native-permissions
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  # Pod for react-native-image-picker
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # Pod for react-native-vector-icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end